name: Run ServeRest API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Newman and Newman HTML Reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Newman tests
        run: |
          newman run ./postman/ServeRest_QA.postman_collection.json \
            -e ./postman/ServeRest_QA_Environment.postman_environment.json \
            -r cli,html \
            --reporter-html-export newman-report.html

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html

